Anpassungen beim Update Verhalten * yahm-ctl fw_update startet die Dienste wieder, wenn kein Update notwendig ist * yahm-lxc update schreibt die gesicherten Dateien nun weg und gibt diese nach dem Update aus * yahm-lxc update kann durch -f veranlasst werden, die letze bekannte Version zum patchen neuer FW-Versionen verwenden zu können Somit kann ein Update auf eine beliebige FW-version vorgenommen werden, auch wenn keine Patches hierfür vorliegen

diff --git a/bin/yahm-lxc b/bin/yahm-lxc
--- a/bin/yahm-lxc
+++ b/bin/yahm-lxc
@@ -92,9 +92,6 @@ create_lxc_container()
         progress "ATTENTION: FORCE-Switch is used, actual instance will be overwritten"
     fi
 
-    # last known configuration
-    LastCCU2Version=$CCU2Version
-
     if [ "${BUILD}" == "" ] 
     then
         CCU2Version=`get_ccu2_actual_version`
@@ -106,12 +103,6 @@ create_lxc_container()
     if [ `yahm_compatibility $CCU2Version` -eq 1 ] && [ $IS_FORCE -ne 1 ]
     then
         die "ERROR: We dont have any patches for this version, please call 'yahm-ctl update' and try again"
-    fi
-
-    # try last known configuration
-    if [ `yahm_compatibility $CCU2Version` -eq 1 ] && [ $IS_FORCE -eq 1 ]
-    then
-        CCU2Version=$LastCCU2Version
     fi
 
     info "Creating new lxc container name: $LXCNAME, version $CCU2Version"
@@ -140,6 +131,11 @@ create_lxc_container()
     progress "Extracting firmware"
     tar $VERBOSE -xzf $EQ3_FW -C $YAHM_TMP
 
+    if [ $? -eq 1 ]
+    then
+        die "Something is wrong with downloaded archive, exit" # SRC Ordner fehlt
+    fi
+
     progress "Extract ubi image"
     $YAHM_DIR/share/tools/ubi_reader/ubi_extract_files.py $QUIET -k -o $LXC_ROOT "${YAHM_TMP}/rootfs.ubi"
 
@@ -153,10 +149,17 @@ create_lxc_container()
         
         if [ ! -f ${YAHM_DIR}/share/firmware/patches/${CCU2Version}.patch ] && [ $IS_FORCE -ne 1 ]
         then
-            die "ERROR: Detected Version: ${CCU2Version}, can not find patch file for this version use -f for patching with version 2.17.16"
+            die "ERROR: Detected Version: ${CCU2Version}, can not find patch file for this version use -f for patching with version ${$LastCCU2Version}"
         else
-            CCU2Version="2.17.16"
+            CCU2Version=$LastCCU2Version
         fi
+    fi
+
+    # try last known configuration
+    if [ `yahm_compatibility $CCU2Version` -eq 1 ] && [ $IS_FORCE -eq 1 ]
+    then
+        info "INFO: No patches for version ${CCU2Version} found, trying to use old patches from ${LastCCU2Version}"
+        CCU2Version=$LastCCU2Version
     fi
 
     if [ $(ver ${CCU2Version}) -ge $(ver "2.17.15") ]
@@ -193,7 +196,8 @@ create_lxc_container()
         echo "lxc.arch = armhf" >> ${LXC_ROOT}/config
     fi
 
-    info "Container is created, please use 'yahm-ctl -n ${LXCNAME} start' to start and 'yahm-ctl -n ${LXCNAME} join' for console access"
+    CCU2current=`get_yahm_version ${LXCNAME}`
+    info "Container version ${CCU2current} is created, please use 'yahm-ctl -n ${LXCNAME} start' to start and 'yahm-ctl -n ${LXCNAME} join' for console access"
     info "For network configuration see yahm-network script"
 
     echo $LXCNAME > ${YAHM_LIB}/container_name
@@ -280,6 +284,11 @@ update_lxc_container()
         die "ERROR: Can not find $LXCNAME container"
     fi
 
+    if [ $(lxc-info -n ${LXCNAME}|grep RUNNING |wc -l) -eq 0 ]
+    then
+        die "${LXCNAME} container is not running (needed for data backup)."
+    fi
+
     if [ "${BUILD}" == "" ]
     then
         CCU2Version=`get_ccu2_actual_version`
@@ -319,13 +328,18 @@ update_lxc_container()
     progress "Backup installed modules"
     cp -rf ${LXC_ROOT}/.modules  ${YAHM_TMP}_update/${LXCNAME}/
     
-    backup_file=$(ls ${YAHM_TMP}_update/${LXCNAME}/*.sbk)
+    data_backup_file=$(ls ${YAHM_TMP}_update/${LXCNAME}/*.sbk)
+    info "INFO: Config backup file location: ${data_backup_file}"
 
     progress "Creating full backup from installed version ${installed_version}, calling: 'yahm-backup full_backup' script"
     if [ $IS_DEBUG -eq 1 ] ; then
         info "Calling: /opt/YAHM/bin/yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} full_backup"
     fi
     /opt/YAHM/bin/yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} full_backup
+
+    mv ${YAHM_TMP}/yahm_backup-${installed_version}.tgz ${YAHM_TMP}_update/${LXCNAME}/yahm_backup-${installed_version}_$(date +%Y%m%d).tgz
+    full_backup_file=$(ls ${YAHM_TMP}_update/${LXCNAME}/yahm_backup-*.tgz)
+    info "INFO: Full backup file location: ${full_backup_file}"
 
     progress "Delete old YAHM Container version: $installed_version"
     if [ $IS_DEBUG -eq 1 ] ; then
@@ -344,9 +358,9 @@ update_lxc_container()
 
     progress "Trying to restore old CCU2 backup, calling 'yahm-backup data_restore'"
     if [ $IS_DEBUG -eq 1 ] ; then
-        info "Calling: yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} -d ${backup_file} data_restore" 
+        info "Calling: yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} -d ${data_backup_file} data_restore"
     fi
-    /opt/YAHM/bin/yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} -d ${backup_file} data_restore
+    /opt/YAHM/bin/yahm-backup ${VERBOSE} ${force_switch} -n ${LXCNAME} -d ${data_backup_file} data_restore
 
     if [ $IS_DEBUG -eq 1 ] ; then
         info "Calling: yahm-ctl -n ${LXCNAME} start"
@@ -355,13 +369,6 @@ update_lxc_container()
 
     progress "Restoring old installed modules"
     files=`ls ${YAHM_TMP}_update/${LXCNAME}/.modules`
-
-    if [ ! -f ${YAHM_TMP}_update/${LXCNAME}/.modules/homematic-ip ] ; then
-        if [ $IS_DEBUG -eq 1 ] ; then
-            info "Calling: /opt/YAHM/bin/yahm-module -n ${LXCNAME} -f -m homematic-ip disable"
-        fi
-        /opt/YAHM/bin/yahm-module -n ${LXCNAME} -f -m homematic-ip disable
-    fi
 
     for file in $files
     do
@@ -373,7 +380,10 @@ update_lxc_container()
     done
 
     #rm -rf ${YAHM_TMP}_update/
-    info "STATUS: Update was successfully new version is: ${CCU2Version}"
+    CCU2current=`get_yahm_version ${LXCNAME}`
+    info "STATUS: Update was successfully new version is: ${CCU2current}"
+    info "STATUS: Old config backup file: ${data_backup_file}"
+    info "STATUS: Old full lxc backup file: ${full_backup_file}"
 }
 
 if [[ $# != 1 ]]; then
